import { createFileRoute, Link } from '@tanstack/react-router';
import { useState, type FormEvent } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable';
import { useShop } from '@/lib/shop-context';
export const Route = createFileRoute('/auth')({ head: () => ({ meta:[{ title:'Your Account — Zejesh Clothes' }, { name:'description', content:'Sign in or create your Zejesh Clothes account to keep your bag and saved pieces.' }, { property:'og:title', content:'Your Account — Zejesh Clothes' }, { property:'og:description', content:'Join Zejesh Clothes and keep your considered collection close.' }, { property:'og:type', content:'website' }, { name:'twitter:card', content:'summary' }] }), component:Auth });
function Auth() {
  const navigate = useNavigate(); const { user } = useShop(); const [mode,setMode] = useState<'signin'|'signup'|'reset'>('signin'); const [email,setEmail] = useState(''); const [password,setPassword] = useState(''); const [busy,setBusy] = useState(false);
  async function submit(e:FormEvent) { e.preventDefault(); setBusy(true); try { if (mode === 'reset') { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo:window.location.origin + '/auth' }); if (error) throw error; toast.success('Check your email for a reset link.'); setMode('signin'); } else if (mode === 'signup') { const { data,error } = await supabase.auth.signUp({ email,password }); if (error) throw error; if (data.session) { toast.success('Welcome to Zejesh.'); await navigate({ to:'/account' }); } else { toast.success('Check your email to confirm your account.'); setMode('signin'); } } else { const { error } = await supabase.auth.signInWithPassword({ email,password }); if (error) throw error; toast.success('Welcome back.'); await navigate({ to:'/account' }); } } catch(err) { toast.error(err instanceof Error ? err.message : 'Please try again.'); } finally { setBusy(false); } }
  async function google() { setBusy(true); try { const result = await lovable.auth.signInWithOAuth('google', { redirect_uri:window.location.origin }); if (result.error) throw result.error; if (!result.redirected) { toast.success('Welcome to Zejesh.'); await navigate({ to:'/account' }); } } catch(err) { toast.error(err instanceof Error ? err.message : 'Google sign-in failed.'); } finally { setBusy(false); } }
  if (user) return <main className="auth-layout"><div className="auth-box text-center"><h1>Welcome back.</h1><p>Your wardrobe awaits.</p><Button asChild><Link to="/account">YOUR ACCOUNT</Link></Button></div></main>;
  return <main className="auth-layout"><div className="auth-box"><span className="eyebrow">ZEJESH / YOUR ACCOUNT</span><h1>{mode === 'signup' ? 'Join the edit.' : mode === 'reset' ? 'Reset password.' : 'Welcome back.'}</h1><p>{mode === 'signup' ? 'Create your account to save what speaks to you.' : mode === 'reset' ? 'We’ll send you a link to reset your password.' : 'A considered wardrobe, always within reach.'}</p><form onSubmit={submit}><label className="form-field">EMAIL ADDRESS<input type="email" required autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label>{mode !== 'reset' && <label className="form-field">PASSWORD<input type="password" required minLength={6} autoComplete={mode === 'signin' ? 'current-password' : 'new-password'} value={password} onChange={e => setPassword(e.target.value)} placeholder="Minimum 6 characters" /></label>}<Button size="wide" className="w-full" disabled={busy} type="submit">{busy ? 'PLEASE WAIT…' : mode === 'signup' ? 'CREATE ACCOUNT' : mode === 'reset' ? 'SEND RESET LINK' : 'SIGN IN'}</Button></form>{mode === 'signin' && <button type="button" className="mt-4 text-xs underline" onClick={() => setMode('reset')}>Forgot password?</button>}{mode !== 'reset' && <><div className="auth-divider">OR</div><Button variant="outline" size="wide" className="w-full" disabled={busy} onClick={google}>CONTINUE WITH GOOGLE</Button></>}<div className="auth-switch">{mode === 'signup' ? 'Already have an account?' : mode === 'reset' ? 'Remember your password?' : 'New to Zejesh?'} <button type="button" onClick={() => setMode(mode === 'signin' ? 'signup' : 'signin')}>{mode === 'signin' ? 'Create an account' : 'Sign in'}</button></div></div></main>;
}
