import { createFileRoute } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { Search } from 'lucide-react';
import { getProducts } from '@/lib/catalog';
import { ProductCard } from '@/components/shop';
export const Route = createFileRoute('/shop')({
  validateSearch: (search: Record<string, unknown>) => ({ category: typeof search.category === 'string' ? search.category : 'All', color: typeof search.color === 'string' ? search.color : 'All', sort: typeof search.sort === 'string' ? search.sort : 'featured', q: typeof search.q === 'string' ? search.q : '' }),
  head: () => ({ meta: [{ title:'Shop the Collection — Zejesh Clothes' }, { name:'description', content:'Explore the Zejesh Clothes collection of modern tailoring, dresses, outerwear, and elevated essentials.' }, { property:'og:title', content:'Shop the Collection — Zejesh Clothes' }, { property:'og:description', content:'Discover considered pieces in the Zejesh Clothes collection.' }, { property:'og:type', content:'website' }, { name:'twitter:card', content:'summary_large_image' }] }), component: Shop,
});
function Shop() {
  const filters = Route.useSearch(); const navigate = Route.useNavigate();
  const { data: products = [], isLoading, isError } = useQuery({ queryKey:['products'], queryFn:getProducts });
  const visible = products.filter(p => (filters.category === 'All' || p.category === filters.category) && (filters.color === 'All' || p.color === filters.color) && (!filters.q || `${p.name} ${p.category} ${p.description}`.toLowerCase().includes(filters.q.toLowerCase()))).sort((a,b) => filters.sort === 'price-asc' ? a.price - b.price : filters.sort === 'price-desc' ? b.price - a.price : filters.sort === 'name' ? a.name.localeCompare(b.name) : Number(b.featured) - Number(a.featured));
  const update = (key: keyof typeof filters, value: string) => navigate({ search: prev => ({ ...prev, [key]:value }), replace:true });
  return <main className="section-wrap"><div className="page-heading"><span className="eyebrow">THE ZEJESH EDIT</span><h1 className="page-title">The collection.</h1></div><div className="shop-toolbar"><div className="search-field"><Search size={16} /><input aria-label="Search pieces" placeholder="Search the collection" value={filters.q} onChange={e => update('q',e.target.value)} /></div><div className="filter-group"><select className="filter-control" aria-label="Category" value={filters.category} onChange={e => update('category',e.target.value)}>{['All','Tailoring','Dresses','Outerwear','Tops'].map(x => <option key={x} value={x}>{x === 'All' ? 'All categories' : x}</option>)}</select><select className="filter-control" aria-label="Color" value={filters.color} onChange={e => update('color',e.target.value)}>{['All','Black','White'].map(x => <option key={x} value={x}>{x === 'All' ? 'All colors' : x}</option>)}</select><select className="filter-control" aria-label="Sort products" value={filters.sort} onChange={e => update('sort',e.target.value)}><option value="featured">Featured</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="name">Name: A–Z</option></select></div><span className="results-count">{visible.length} PIECES</span></div>{isLoading ? <div className="empty-state">Loading collection…</div> : isError ? <div className="empty-state"><h2>Something went wrong.</h2><p>Please try again shortly.</p></div> : visible.length ? <div className="product-grid">{visible.map((p,i) => <ProductCard product={p} index={i} key={p.id} />)}</div> : <div className="empty-state"><h2>No pieces found.</h2><p>Try a different search or selection.</p></div>}</main>;
}
